### PR TITLE
F/cost object api

### PR DESCRIPTION
**Pull request by tormodAase**
This PR implements Cost Objects API. The user should now be able to search cost centers and WBSes

### CODE REVIEW

**Review by dbjoEq — DISMISSED** [review]
Looks good.

**Comment by tormodAase** [comment]
attachment branch got merged into main, so I merged main into this branch and need a re-review. The only merge conflict was in store.ts

**Review by dbjoEq — DISMISSED** [review]
Good job. 👍

**Comment by tormodAase** [comment]
Fixed a placeholder text

**Review by dbjoEq — APPROVED** [review]
Looks good. 👍

**Pull request merged**
